# Laborator 2

Continut:
1. Exercitii cu functii
1. Exercitii cu NumPy

Precizari:
1. Studentii se pot consulta reciproc, dar rezolvarile vor fi individuale. Daca la o problema nu se pot furniza explicatii legate de rezolvare, nota pentru intreaga tema va fi 0. 
1. Temele se predau in activitatea de elearning asociata, pana in 21 octombrie 2022 ora 23. Se acorda 2 puncte din oficiu.
1. Tema va fi implementata intr-un singur fisier Jupyter Notebook, avand numele: Tema2_IDS_nume_prenume.ipynb. Exemplu: Tema2_IDS_Popescu_Ioana.ipynb
1. Se vor folosi type annotations pentru variabile, parametrii functiilor, tipuri de retur. Se vor folosi docstrings pentru functii, in limba romana sau engleza. Neindeplinirea acestei cerinte duce la injumatatirea punctajului pe exercitiul in cauza.

Pentru docstring exista 3 stiluri de lucru. Exemple scurte sunt la [https://stackoverflow.com/questions/3898572/what-is-the-standard-python-docstring-format](https://stackoverflow.com/questions/3898572/what-is-the-standard-python-docstring-format). Se va folosi stilul reST, recomandat de [PEP287](https://www.python.org/dev/peps/pep-0287/).

In [198]:
import numpy as np
from typing import List

## Exercitii cu functii

1 (1 punct). Scrieti o functie care primeste un numar intreg si returneaza produsul cifrelor sale. 

In [199]:
def produsul_cifrelor(numar: int) -> int:
    """
    Computes the product of a number's digits.
    
    :param number: the given number
    
    :returns: the product of a number's digits
    """
    if numar == 0:
        return 0
    
    nr: str = str(numar)
    cifre: List[int] = [int(char) for char in nr if char.isdigit()]
    produs: int = np.prod(cifre)
    return produs

produsul_cifrelor(-1.8)

8

2 (1 punct). Scrieti o functie care determina daca un sir de caractere - presupus a fi scris cu litere mici - este sau nu palindrom. Un palindrom este un sir de caractere care citit de la dreapta la stanga are acelasi continut ca si citirea de la stanga la dreapta. In functie de valoarea unui indicator boolean `ignore_spaces`, avand valoarea implicita `False`, se vor ignora (elimina) sau nu spatiile. Daca sirul dat ca parametru nu are toate literele mici, se va arunca exceptie; [documentatie pentru lucrul cu exceptii in Python](https://www.w3schools.com/python/gloss_python_raise.asp).

Exemple:

* `is_palindrome('ele fac cafele', ignore_spaces=True)` returneaza `True`; `is_palindrome('ele fac cafele')` returneaza `False`. `is_palindrome('Ele fac cafele')` arunca o exceptie, indiferent de valoarea lui `ignore_spaces`.
*  `is_palindrome('abaac')` returneaza `False`

In [200]:
def is_palindrome (string: str, ignore_spaces: bool = False) -> bool:
    '''
    Determines if the given string is palindrome.
    
    :param string: string to be verified
    :param ignore_spaces: determines if spaces are ignored
        
    :returns: True if the string is palindrome, False otherrwise 
    '''
    if any((character != character.lower()) for character in string):
        raise Exception("Exista litere mari!")
        
    if ignore_spaces == True:
        string = string.replace(" ", "")
        
    return string == string[::-1]

is_palindrome('ele fac cafele', ignore_spaces=True)

True

3 (1 punct). Se da un fisier de tip text, pentru care se vor considera doar acele linii din fisier care contin exact un numar intreg. Sa se scrie functii care:
* returneaza doar lista numerelor 'valide' - folosita mai departe ca functie auxiliara;
* determina daca numerele din fisier sunt sau nu distincte, returnand `True` respectiv `False`;
* returneaza cele mai mari 3 numere din fisier, in ordine descrescatoare;
* produce lista tuturor tripletelor distincte `(x, y, z)` cu `(x < y < z)`, unde `x, y, z` sunt valori din fisier.

Exemplu: pentru continutul de fisier
```
#1
2
4
-4
3
-3
10
2
abc
100 1
```
functiile vor returna, respectiv:
* `[2, 4, -4, 3, -3, 10, 2]`
* `False`
* `[10, 4, 3]`
* ```[(-4, -3, 2), (-4, -3, 3), (-4, -3, 4), (-4, -3, 10), (-4, 2, 3), (-4, 2, 4), (-4, 2, 10), (-4, 3, 4), (-4, 3, 10), (-4, 4, 10), (-3, 2, 3), (-3, 2, 4), (-3, 2, 10), (-3, 3, 4), (-3, 3, 10), (-3, 4, 10), (2, 3, 4), (2, 3, 10), (2, 4, 10), (3, 4, 10)]```

Pentru lucrul cu fisiere, puteti consulta, de exemplu: https://www.w3schools.com/python/python_file_open.asp, https://www.geeksforgeeks.org/reading-writing-text-files-python/.

In [201]:
import re

In [203]:
def is_valid_int(string: str) -> bool:
    """
    Checks if the given string is an int.
    
    :param string: the given string
    
    :returns: True if the string is an int, False otherwise.
    """
    result: re.Match = re.match("^[-+]?[0-9]+$", string)
    return result is not None

is_valid_int('-21')

True

In [204]:
def get_valid_numbers(file_name: str) -> List[int]:
    """
    Returns a list of valid numbers found in a file.
    
    :param file_name: the file's name
    
    :return: the list of valid numbers found
    """
    valid_numbers: List[int] = []
    with open(file_name, 'rt') as f:
        file_lines: List[str] = f.readlines()
    file_lines = [line.strip('\n') for line in file_lines]
    valid_numbers: List[int] = [int(x) for x in file_lines if is_valid_int(x)]
    
    return valid_numbers

get_valid_numbers("tema2_fis.txt")

[2, 4, -4, 3, -3, 10, 2]

In [205]:
def distinct_numbers(file_name: str) -> bool:
    """
    Checks if the numbers from a file are distinct.
    
    :param file_name: file's name
    
    :return: True if the valid numbers found in file are distinct, False otherwise
    """
    valid_numbers: List[int] = get_valid_numbers(file_name)
    return len(valid_numbers) == len(set(valid_numbers))
    
distinct_numbers("tema2_fis.txt")

False

In [211]:
def get_gratest_3(file_name: str) -> List[int]:
    """
    Returns the 3 gratest numbers found in a file.
    
    :param file_name: file's name
    
    :return: list containing gratest 3 numbers found in file
    """
    valid_numbers: List[int] = get_valid_numbers(file_name)
    valid_numbers.sort(reverse=True)
    return valid_numbers[:3]

get_gratest_3("tema2_fis.txt")

[10, 4, 3]

In [212]:
def get_triplets(file_name: str) -> List[int]:
    """
    Searches for distinct triplets of numbers (x, y, z) found in a file that respect the condition: x < y < z.
    
    :param file_name: file's name
    
    :return: set of triplets that respect the condition found in file
    
    """
    valid_numbers = get_valid_numbers(file_name)
    valid_numbers.sort()
    valid_size = len(valid_numbers)
    triplets = [(valid_numbers[x], valid_numbers[y], valid_numbers[z]) 
                for x in range(valid_size) 
                for y in range(x, valid_size)
                for z in range(y, valid_size)
                if valid_numbers[x] < valid_numbers[y] < valid_numbers[z]]
    
    return set(triplets)

get_triplets("tema2_fis.txt")

{(-4, -3, 2),
 (-4, -3, 3),
 (-4, -3, 4),
 (-4, -3, 10),
 (-4, 2, 3),
 (-4, 2, 4),
 (-4, 2, 10),
 (-4, 3, 4),
 (-4, 3, 10),
 (-4, 4, 10),
 (-3, 2, 3),
 (-3, 2, 4),
 (-3, 2, 10),
 (-3, 3, 4),
 (-3, 3, 10),
 (-3, 4, 10),
 (2, 3, 4),
 (2, 3, 10),
 (2, 4, 10),
 (3, 4, 10)}

4. Sa se scrie o functie `sum_divisors_digits`care preia un numar natural strict pozitiv $n$ si returneaza suma cifrelor divizorilor sai. Intr-o alta functie `black_hole` se apeleaza in mod repetat `sum_divisors_digits` pe numerele rezultate, pana cand se atinge un numar maxim de iteratii (implicit 1000) sau se ajunge la numarul 15. Puteti crea alte  functii auxiliare. 

Exemplul 1: se pleaca de la $n=15$; divizorii sunt $1, 3, 5, 15$; suma cifrelor divizorilor este $1+3+5+1+5=15$, acesta fiind rezultatul apelului `sum_divisors_digits(15)`. Functia `black_hole` se opreste deci dupa un singur apel al functiei `sum_divisors_digits`.

Exemplul 2: se pleaca de la $n=21$; divizorii sunt $1, 3, 7, 21$ iar `sum_divisors_digits(21)` este $1+3+7+2+1=14$; se reia in functia `black_hole` apelul functiei `sum_divisors_digits` pana la epuizarea numarului de apeluri sau potentiala stabilizare in 15.

In [215]:
def get_sum_of_digits(number: int) -> int:
    """
    Computes the sum of an integer number's digits.
    
    :param number: the given integer number
    
    :return: the computed sum
    
    """
    return sum([int(digit) for digit in str(number)])

In [214]:
def sum_divisors_digits(number: int) -> int:
    """
    Computes the sum of an integer number's divisorss digits.
    
    :param number: the given integer number
    
    :return: the computed sum
    """
    divisors: list = [index for index in range(1, number + 1) if number % index == 0]
    return sum([get_sum_of_digits(divisor) for divisor in divisors] )

In [348]:
def black_hole(number: int, no_max_of_it: int = 1000) -> None:
    """
    Calls sum_divisors_digits on the given number and then calls repeatedly sum_divisors_digits on the resulting 
    numbers, until a maximum number of iterations or the number 15 is reached.
    
    :param number: the given number
    :no_max_of_it: the maximum number of iterations
    
    :return: none
    """
    it = 0
    while number != 15 and it < no_max_of_it or it == 0:
        number = sum_divisors_digits(number)
        it += 1
    print(f'{it} apeluri ale functiei sum_divisors_digits')

In [220]:
black_hole(21)
black_hole(15)

2 apeluri ale functiei sum_divisors_digitscare
1 apeluri ale functiei sum_divisors_digitscare


## Exercitii cu NumPy

In rezolvarea exercitiilor de mai jos se va folosi cod *vectorizat* si collection comprehension (preferabil insa doar cod vectorizat). Puteti folosi functii NumPy.

1. (1 punct) Scrieti o functie care pentru un vector dat $a$ dat de $n$ componente, returneaza un vector suma perechilor de elemente: $b[i] = a[i]+a[i+1], 0 \le i \le n-2$. Scrieti apoi o alta functie care face acelasi lucru pentru o matrice, pe linii sau pe coloane, in functie de un parametru.

Exemple: 
* `a = np.array([1, 2, 10, 3])`; `sum_pairs_vector(a)` va returna vectorul NumPy cu continutul `(3, 12, 13)`.
* `a  = np.array([[1, 2, 3], [40, 50, 60]])`; `sum_pairs_matrix(a, on='columns')` returneaza o matrice cu o singura linie, `[[41, 52, 63]]`. `sum_pairs_matrix(a, on='rows)` returneaza matricea `[[3, 5], [90, 110]]`. 

Rows
$$
\begin{bmatrix}
a1 & a2\\
a3 & a4
\end{bmatrix}
=>
\begin{bmatrix}
a1+a2 \\
a3+a4
\end{bmatrix}
= 
\begin{bmatrix}
a1 \\
a3
\end{bmatrix}
+
\begin{bmatrix}
a2 \\
a4
\end{bmatrix}
$$ 

In [222]:
def sum_pairs_vector(vector: np.ndarray) -> np.ndarray:
    """
    Computes the sum of pairs of elements: 𝑏[𝑖] = 𝑎[𝑖]+𝑎[𝑖+1], 0 ≤ 𝑖 ≤ 𝑛−2 on an 1d array.
    
    :param vector: the initial 1d array
    
    :return: the computed sum 
    """
    if len(vector) < 2:
        return None
    return vector[:-1] + vector[1:] 

sum_pairs_vector(vector=np.array([1]))

Columns
$$
\begin{bmatrix}
a1 & a2\\
a3 & a4
\end{bmatrix}
=>
\begin{bmatrix}
a1+a3 & a2+a4
\end{bmatrix}
= 
\begin{bmatrix}
a1 & a2
\end{bmatrix}
+
\begin{bmatrix}
a3 & a4
\end{bmatrix}
$$ 

In [223]:
def sum_pairs_matrix(matrix: np.ndarray, on: str) -> np.ndarray:
    """
    Computes the sum of pairs of elements: 𝑏[𝑖] = 𝑎[𝑖]+𝑎[𝑖+1], 0 ≤ 𝑖 ≤ 𝑛−2 on rows / columns for an 2d array.
    
    :param vector: the initial array
    :param on: if the sum should be cmputed on rows or columns
    
    :return: the computed sum 
    """
    if on == 'columns':
        return matrix[:-1,:] + matrix[1:,:]
    
    if on =='rows':
        return matrix[:,:-1] + matrix[:,1:]

In [224]:
sum_pairs_matrix(np.array([[1, 2, 3], [40, 50, 60]]), on='rows')

array([[  3,   5],
       [ 90, 110]])

In [225]:
sum_pairs_matrix(np.array([[1, 2, 3], [40, 50, 60]]), on='columns')

array([[41, 52, 63]])

2. (1 punct) Sa se scrie o functie care primeste o matrice de numere si determina daca numarul de valori aflate in intervalul $(-lim, lim)$ ($lim$ > 0, parametru al functiei, numar real) este peste un procent $p$, parametru dat. Functia va returna valoare booleana. 

In [339]:
matrix = np.array([[1,2], [3,4], [-3, 100]])

In [343]:
def is_in_interval(matrix: np.ndarray, lim: float, p: float):
    """
    Determines if the number of values in the interval (−𝑙𝑖𝑚,𝑙𝑖𝑚) is over a higher percentage.
    
    :param matrix: the given array
    :param lim: the limit, 𝑙𝑖𝑚 > 0
    :param p: the given percentage
    
    :return: True if the number of values in the interval is higher a given percentage, False otherwise
    
    """
    no_in_interval = np.count_nonzero((matrix < lim) & (-lim < matrix))
    percentage = no_in_interval * 100 / matrix.size
    return percentage > p

print(is_in_interval(matrix, 3, 50))
print(is_in_interval(matrix, 5, 50))

False
True


3. (1 punct) Sa se scrie o functie care gaseste pozitiile minimelor locale dintr-un vector numpy. Un minim local este o valoare care are in vecinii imediati (indicele curent $\pm 1$, fara a iesi din vector) valori strict mai mari decat ea. 

Exemplu: `[-1, 3, -7, 1, 2, 6, 0, 1]` -> `[-1, -7, 0]`.

In [344]:
def minime_locale(array: np.ndarray) -> np.ndarray:
    """
    Computes the local minimums from a given array.
    
    :param array: the array
    
    :return: the pozitions of the local miniums
    """
    previous_is_greater = np.append(True, array[1:] < array[:-1])
    next_is_greater = np.append(array[:-1] < array[1:], True)
    minime = np.logical_and(previous_is_greater, next_is_greater)
        
    return np.where(minime == True)

In [345]:
array = np.array([-1, 3, -7, 1, 2, 6, 0, 1])
pozitii = minime_locale(array)
print(pozitii)
print(array[pozitii])

(array([0, 2, 6], dtype=int64),)
[-1 -7  0]


4. (1 punct) Sa se scrie o functie care spune daca o matrice patratica este magica: suma pe fiecare linie, pe fiecare coloana, suma elementelor de pe fiecare diagonala este acelasi numar.

Exemplu de matrice magica:
```
11	24	7	20	3
4	12	25	8	16
17	5	13	21	9
10	18	1	14	22
23	6	19	2	15
```

In [346]:
def is_magic_matrix(matrix: np.ndarray) -> bool:
    """
    Determines if the given 2d array is a magic matrix.
    
    :param matrix: the given matrix
    
    :return: True if the matrix is magic, False otherwise
    """
    if matrix.shape[0] != matrix.shape[1]:
        return False
    
    sum_rows = matrix.sum(axis=1)
    sum_rows_equal = np.all(sum_rows == sum_rows[0])
    
    sum_columns = matrix.sum(axis=0)
    sum_columns_equal = np.all(sum_columns == sum_columns[0])
    
    sum_first_diagonal = np.trace(matrix)
    matrix = np.fliplr(matrix)
    sum_second_diagonal = np.trace(matrix)
    
    return (sum_rows_equal and sum_columns_equal and 
            sum_rows[0] == sum_columns[0] and
            sum_first_diagonal == sum_rows[0] and 
            sum_second_diagonal == sum_columns[0])


In [347]:
matrix = np.array(
    [[11, 24, 7, 20, 3],
    [4, 12, 25, 8, 16],
    [17, 5, 13, 21, 9],
    [10, 18, 1, 14, 22],
    [23, 6, 19, 2, 15]])

is_magic_matrix(matrix)

True